{
 "title": "${SIMULATION_NAME}",
 "tags": [ "Rhino PAP" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Test Users",
   "type": "gauge",
   "description": "Number of nodes\n",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Users",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "user_${SIMULATION_NAME}",
     "query": "SELECT count(distinct(\"id\")) FROM \"user_${SIMULATION_NAME}\" WHERE $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load nodes",
   "type": "gauge",
   "description": "Number of nodes\n",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "Nodes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "query": "SELECT count(distinct(\"node\")) FROM \"simulation_${SIMULATION_NAME}\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "node" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "description": "Number of nodes\n",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "RT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "query": "SELECT count(distinct(\"node\")) FROM \"simulation_${SIMULATION_NAME}\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "pt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Requests (per Second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "select": [
      [
       { "params": [ "pt" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scenario: ${SCENARIO_1}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "alias": "Mean Response Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "query": "SELECT mean(\"pt\") FROM \"${SCENARIO_1}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "step" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "query": "SELECT distinct(\"pt\") FROM \"simulation_${SIMULATION_NAME}\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "pt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "simulation_${SIMULATION_NAME}",
     "query": "SELECT distinct(\"pt\") FROM \"simulation_${SIMULATION_NAME}\" WHERE $timeFilter GROUP BY time($__interval), \"step\" fill(null)",
     "select": [
      [
       { "params": [ "pt" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}