#!/bin/bash

#
#
# ADOBE CONFIDENTIAL
# ___________________
#
#  Copyright 2018 Adobe Systems Incorporated
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Adobe Systems Incorporated and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Adobe Systems Incorporated and its
# suppliers and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Adobe Systems Incorporated.

#
# rhino: loadtesting CLI host script.
# -
# version   1.0
# author    Erhan Bagdemir <bagdemir@adobe.com>

#-----------------------------------------------------------------------
# Print functions
#-----------------------------------------------------------------------
p_list()
{
  local arr=($@)
  local prefix=${2-""}
  local suffix=${3-""}

  for t in ${!arr[@]}; do
    printf "  %2d. %s\n" "$((t+1))" "${arr[$t]}"
  done

  echo ""
  echo "Total ${#arr[@]} found."
}

p_header()
{
  echo ""
  printf "%s\n" "$1"
}

p_status()
{
  printf "* %-100s [%s]\n" "$2" "$1"
}

p_ln()
{
  printf "  %s\n" "$1"
}

p_err()
{
  local res=$1
  printf "%s\n" "$res"
  [[ $res =~ .*ExpiredTokenException.* ]] && echo "Token expired? Use KLAM: https://klam-sj.corp.adobe.com to renew your token."
  [[ $res =~ .*security\ token.*invalid.* ]] && echo "Token expired? Use KLAM: https://klam-sj.corp.adobe.com to renew your token."

  exit 1
}