#!/bin/bash

#
#
# ADOBE CONFIDENTIAL
# ___________________
#
#  Copyright 2018 Adobe Systems Incorporated
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Adobe Systems Incorporated and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Adobe Systems Incorporated and its
# suppliers and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Adobe Systems Incorporated.

#
# rhino: loadtesting CLI host script.
# -
# version   1.0
# author    Erhan Bagdemir <bagdemir@adobe.com>

declare -r RHINO_HOME="${RHINO_HOME:-${HOME}/.rhino}"
declare -r REPORTING_DIR="${REPORTING_DIR:-${RHINO_HOME}/results}"
declare -r ENV_FILE="${ENV_FILE:-${RHINO_HOME}/env}"

# -v ${RHINO_HOME}/templates:/root/.rhino/templates \
docker run -it  \
    -v ${REPORTING_DIR}:/opt/gatling/results \
    -v ${RHINO_HOME}/cache/rhino-cli:/usr/local/rhino \
    --env-file $ENV_FILE \
    -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
    rhino:latest $@
